version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb2:/var/lib/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=rootpassword
      - DOCKER_INFLUXDB_INIT_ORG=gologic
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=abcdef
volumes:
  influxdb2: